[build]
  base = "www/"
  publish = "_site/"  # relative to `base` directory
  command = "./combine-versions.sh && bundle exec jekyll build"

  [build.environment]
    BUNDLE_GEMFILE = "Gemfile"

[context.deploy-preview]
  command = "./combine-versions.sh && bundle exec jekyll build --drafts --future"
