# Mapping from version in the URL to the key in site.data.nav.
url_to_key:
  draft: draft
  v0.1: v01
  v0.2: v02
  v1.0-rc1: v10-rc1
  v1.0-rc2: v10-rc2
  v1.0: v10
  v1: v10
  v1-rc1: v10-rc1
  v1-rc2: v10-rc2
  v1.1: v11
  latest: v10

# TODO: when viewing spec v0.1, it would be better to link to attestations v0.2.
# Not sure how to implement that though.
